import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { BottomNavigationPremium } from '@/components/BottomNavigationPremium';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { recognizePriceFromImage, type OcrAmountResult } from '@/services/ocr.service';
import { exchangeRateService } from '@/services/exchange-rate.service';
import type { SupportedCountryCode } from '@/services/types';
import { COLORS, RADIUS, SHADOWS, SIZES, SPACING, TYPOGRAPHY } from '@/constants/design';

type ScanTab = 'home' | 'scan' | 'input' | 'history' | 'voice' | 'rate' | 'settings';
export function ScanScreen({ countryCode, onBack, onNavigate }: { countryCode: SupportedCountryCode; onBack: () => void; onNavigate: (tab: ScanTab) => void }) {
  const [result, setResult] = useState<OcrAmountResult | null>(null); const [loading, setLoading] = useState(false);
  const pick = async (source: 'camera' | 'gallery') => { const response = source === 'camera' ? await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: 0.8 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 }); if (response.canceled) return; setLoading(true); setResult(null); try { setResult(await recognizePriceFromImage(response.assets[0].uri, countryCode, source)); } catch { Alert.alert('인식할 수 없습니다', '가격이 잘 보이는 사진을 선택해 주세요.'); } finally { setLoading(false); } };
  return <SafeAreaView edges={['top']} style={styles.screen}><View style={styles.layout}><ScreenHeader title="가격 스캔" showBack onBackPress={onBack} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.title}>메뉴판을 촬영하세요</Text><Text style={styles.description}>가격이 화면 안에 들어오도록 맞춰주세요.</Text>
    <View style={styles.preview}><View style={styles.scanFrame}><Text style={styles.scanIcon}>▣</Text><Text style={styles.scanFrameText}>가격을 이 영역에 맞춰주세요</Text></View></View>
    <View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel="카메라로 가격표 촬영" onPress={() => void pick('camera')} style={styles.primaryAction}><Text style={styles.actionIcon}>⌾</Text><Text style={styles.primaryText}>사진 촬영</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="갤러리에서 가격표 선택" onPress={() => void pick('gallery')} style={styles.secondaryAction}><Text style={styles.actionIcon}>▧</Text><Text style={styles.secondaryText}>갤러리 선택</Text></Pressable></View>
    {loading && <View accessibilityLiveRegion="polite" style={styles.loading}><ActivityIndicator color={COLORS.primary} size="large" /><Text style={styles.loadingTitle}>가격을 확인하고 있어요</Text><Text style={styles.loadingText}>사진에서 가격과 메뉴를 찾는 중입니다.</Text></View>}
    {result && <View style={styles.result}><Text style={styles.resultTitle}>인식 결과</Text><Text style={styles.raw}>원문: {result.rawText}</Text>{result.items.map((item, index) => { const rate = exchangeRateService.getRate(item.currency); const krw = exchangeRateService.formatKrw(exchangeRateService.calculateKrw(item.amount, item.currency)); return <View key={`${item.currency}-${item.amount}-${index}`} style={styles.item}>{item.translatedMenuName && <Text style={styles.menu}>{item.translatedMenuName}</Text>}<Text style={styles.local}>{new Intl.NumberFormat('ko-KR').format(item.amount)} {item.currency}</Text><Text style={styles.resultArrow}>↓</Text><Text style={styles.krw}>{krw}</Text><Text style={styles.rate}>1,000 {item.currency} ≈ {Math.round(rate.rateToKrw * 1000).toLocaleString('ko-KR')} KRW</Text></View>; })}</View>}
  </ScrollView><BottomNavigationPremium activeTab="scan" onTabChange={onNavigate} onScanPress={() => onNavigate('scan')} /></View></SafeAreaView>;
}
const styles = StyleSheet.create({ screen:{flex:1,backgroundColor:COLORS.background},layout:{flex:1,justifyContent:'space-between'},content:{width:'100%',maxWidth:640,alignSelf:'center',padding:SIZES.screenPadding,paddingBottom:SPACING.xxl},title:{...TYPOGRAPHY.heading,color:COLORS.textPrimary},description:{...TYPOGRAPHY.bodyMedium,color:COLORS.textSecondary,marginTop:SPACING.xs},preview:{height:240,marginTop:SPACING.lg,borderRadius:SIZES.cardRadius,backgroundColor:'#E8F0FF',borderWidth:1,borderColor:COLORS.borderLight,alignItems:'center',justifyContent:'center',overflow:'hidden'},scanFrame:{width:'78%',height:'68%',borderWidth:2,borderColor:COLORS.primary,borderRadius:SIZES.cardRadius,alignItems:'center',justifyContent:'center',borderStyle:'dashed'},scanIcon:{fontSize:44,color:COLORS.primary},scanFrameText:{...TYPOGRAPHY.bodySmall,color:COLORS.primary,marginTop:SPACING.sm},actions:{flexDirection:'row',gap:SPACING.md,marginTop:SPACING.lg},primaryAction:{flex:1,minHeight:SIZES.buttonHeight,borderRadius:RADIUS.md,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center'},secondaryAction:{flex:1,minHeight:SIZES.buttonHeight,borderRadius:RADIUS.md,backgroundColor:COLORS.surface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:COLORS.border},actionIcon:{fontSize:22,marginBottom:SPACING.xs},primaryText:{...TYPOGRAPHY.bodyMedium,color:COLORS.surface,fontWeight:'700'},secondaryText:{...TYPOGRAPHY.bodyMedium,color:COLORS.primary,fontWeight:'700'},loading:{alignItems:'center',gap:SPACING.sm,marginTop:SPACING.lg,padding:SPACING.xxl,borderRadius:SIZES.cardRadius,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.borderLight,...SHADOWS.sm},loadingTitle:{...TYPOGRAPHY.subheading,color:COLORS.textPrimary},loadingText:{...TYPOGRAPHY.bodySmall,color:COLORS.textSecondary,textAlign:'center'},result:{marginTop:SPACING.lg,padding:SPACING.xl,borderRadius:SIZES.cardRadius,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.borderLight,...SHADOWS.sm},resultTitle:{...TYPOGRAPHY.subheading,color:COLORS.textPrimary},raw:{...TYPOGRAPHY.captionSmall,color:COLORS.textSecondary,marginTop:SPACING.sm},item:{borderTopWidth:1,borderTopColor:COLORS.border,paddingTop:SPACING.lg,marginTop:SPACING.lg},menu:{...TYPOGRAPHY.subheading,color:COLORS.textPrimary},local:{...TYPOGRAPHY.body,color:COLORS.textPrimary,fontWeight:'700',marginTop:SPACING.sm},resultArrow:{fontSize:18,color:COLORS.textTertiary,marginVertical:2},krw:{...TYPOGRAPHY.heading,color:COLORS.primary},rate:{...TYPOGRAPHY.captionSmall,color:COLORS.textSecondary,marginTop:SPACING.xs}});
